<?php
return [
	'models'=>[
		'info'=>'信息模型',
		'product'=>'商城模型',
		'page'=>'单页模型',
	],
	'types'=>[
		1=>'栏目',
		'单页',
		'网址',
	],
	'forms'=>[
		'info'=>'信息表单',
		'product'=>'商品表单',
		'page'=>'单页表单',
	],
	'list_forms'=>[
		'list_info'=>'信息列表',
		'list_product'=>'商品列表',
		'list_page'=>'单页列表',
	],
	'search_forms'=>[
		'search_info'=>'信息搜索',
		'search_product'=>'商品搜索',
		'search_page'=>'单页搜索',
	],
	'layout_views'=>[
		'layout_info'=>'信息布局视图',
		'layout_product'=>'商品布局视图',
		'layout_page'=>'单页布局视图',
	],
	'index_views'=>[
		'index_info'=>'信息首页视图',
		'index_product'=>'商品首页视图',
		'index_page'=>'单页首页视图',
	],
	'cat_views'=>[
		'cat_info'=>'信息栏目视图',
		'cat_product'=>'商品栏目视图',
		'cat_page'=>'单页栏目视图',
	],
	'list_views'=>[
		'list_info'=>'信息列表视图',
		'list_product'=>'商品列表视图',
		'list_page'=>'单页列表视图',
	],
	'search_views'=>[
		'search_info'=>'信息搜索视图',
		'search_product'=>'商品搜索视图',
		'search_page'=>'单页搜索视图',
	],
	'show_views'=>[
		'show_info'=>'信息显示视图',
		'show_product'=>'商品显示视图',
		'show_page'=>'单页显示视图',
	],
];