<?php
return [
	'tab_form',
	'name'=>'category',
	[
		[
			'tab',
			'text'=>'基本信息',
			'name'=>'category_info',
			[
				'template'=>'row',
				'attr_class'=>'form-control',
				[	
					'text',
					'text'=>'栏目名称',
					'name'=>'name',
					'validators'=>[
						['required'],
					],
				],
				[	
					'fileinput',
					'text'=>'栏目图片',
					'name'=>'image',
					'validators'=>[
						['required'],
					],
				],
				[	
					'select',
					'text'=>'栏目类型',
					'name'=>'type',
					'attr_class'=>'form-select',
					'items'=>xq_p('types'),
					'filters'=>['int'],
				],
				'url',
				[	
					'select',
					'text'=>'数据模型',
					'name'=>'model',
					'attr_class'=>'form-select',
					'items'=>xq_p('models'),
				],
				[
					'check',
					'text'=>'应用到子栏目',
					'name'=>'apply_children_model',
					'attr_value'=>1,
					'template'=>'switch',
					'filters'=>['int'],
				],
				'switch',
			],
		],
		[
			'tab',
			'text'=>'SEO信息',
			'name'=>'category_seo',
			[
				'template'=>'row',
				'attr_class'=>'form-control',
				'seo_title',
				'seo_keyword',
				'seo_desc',
			],
		],
		[
			'tab',
			'text'=>'表单设置',
			'name'=>'category_form',
			[
				'template'=>'row',
				'attr_class'=>'form-control',
				[
					'select',
					'text'=>'表单',
					'name'=>'form',
					'attr_class'=>'form-select',
					'items'=>xq_p('forms'),
				],
				[
					'select',
					'text'=>'列表表单',
					'name'=>'list_form',
					'attr_class'=>'form-select',
					'items'=>xq_p('list_forms'),
				],
				[
					'select',
					'text'=>'搜索表单',
					'name'=>'search_form',
					'attr_class'=>'form-select',
					'items'=>xq_p('search_forms'),
				],
				[
					'check',
					'text'=>'应用到子栏目',
					'name'=>'apply_children_form',
					'attr_value'=>1,
					'template'=>'switch',
					'filters'=>['int'],
					
				],
			],
		],
		[
			'tab',
			'text'=>'模板设置',
			'name'=>'category_view',
			[
				'template'=>'row',
				'attr_class'=>'form-control',
				[
					'select',
					'text'=>'布局模板',
					'name'=>'layout_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('layout_views'),
				],
				[
					'select',
					'text'=>'首页模板',
					'name'=>'index_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('index_views'),
				],
				[
					'select',
					'text'=>'栏目页模板',
					'name'=>'category_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('cat_views'),
				],
				[
					'select',
					'text'=>'列表页模板',
					'name'=>'list_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('list_views'),
				],
				[
					'select',
					'text'=>'搜索模板',
					'name'=>'search_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('search_views'),
				],
				[
					'select',
					'text'=>'详细页模板',
					'name'=>'show_view',
					'attr_class'=>'form-select',
					'items'=>xq_p('show_views'),
				],
				[
					'check',
					'text'=>'应用到子栏目',
					'name'=>'apply_children_view',
					'attr_value'=>1,
					'template'=>'switch',
					'filters'=>['int'],
					
				],
			],
		],
		[
			'tab',
			'text'=>'显示设置',
			'name'=>'category_show',
			[
				
				[
					'div',
					'attr_class'=>'form-group row',
					[
						'template'=>'one',
						'attr_class'=>'form-control',
						[
							'number',
							'text'=>'首页推荐数量',
							'name'=>'i_r_num',
							'filter'=>['int'],
							
						],
						[
							'number',
							'text'=>'手机首页推荐数量',
							'name'=>'m_i_r_num',
							'filter'=>['int'],
						],
					],
				],
				[
					'div',
					'attr_class'=>'form-group row',
					[
						'template'=>'one',
						'attr_class'=>'form-control',
						[
							'number',
							'text'=>'首页栏目数量',
							'name'=>'i_c_num',
							'filter'=>['int'],
						],
						[
							'number',
							'text'=>'手机首页栏目数量',
							'name'=>'m_i_c_num',
							'filter'=>['int'],
						],
					],
				],
				[
					'div',
					'attr_class'=>'form-group row',
					[
						'template'=>'one',
						'attr_class'=>'form-control',
						[
							'number',
							'text'=>'列表页分页数量',
							'name'=>'l_page_num',
							'filter'=>['int'],
						],
						[
							'number',
							'text'=>'手机列表页分页数量',
							'name'=>'m_l_page_num',
							'filter'=>['int'],
						],
					],
				],
				[
					'div',
					'attr_class'=>'form-group row',
					[
						'template'=>'one',
						'attr_class'=>'form-control',
						[
							'number',
							'text'=>'列表页推荐数量',
							'name'=>'l_r_num',
							'filter'=>['int'],
						],
						[
							'number',
							'text'=>'手机列表页推荐数量',
							'name'=>'m_l_r_num',
							'filter'=>['int'],
						],
					],
				],
				[
					'div',
					'attr_class'=>'form-group row',
					[
						'template'=>'one',
						'attr_class'=>'form-control',
						[
							'number',
							'text'=>'详细页推荐数量',
							'name'=>'d_r_num',
							'filter'=>['int'],
						],
						[
							'number',
							'text'=>'手机详细页推荐数量',
							'name'=>'m_d_r_num',
							'filter'=>['int'],
						],
					],
				],
				[
					'check',
					'text'=>'应用到子栏目',
					'name'=>'apply_show_subcategory',
					'attr_value'=>1,
					'template'=>'switch',
					'filters'=>['int'],
					
				],
			],
		],
	],
	'event'=>[
		'beforeBind'=>function($form){
			$controller=\xqkeji\App::getController();
			$actionName=$controller->getActionName();
			$data=$form->getData();
			
			if(!isset($data['status']))
			{
				$data['status']=0;
			}

			$form->setData($data);
		}
	],
];
